openapi: 3.0.0
info:
  version: 1.0.0
  title: AfterMeal API Docs
  description: 에프터밀 API 엔드포인트(Endpoint)와 객체 정보, 파라미터, 요청 및 응답 예제를 살펴보세요.

servers:
  # Added by API Auto Mocking Plugin
  - description: SwaggerHub API Auto Mocking
    url: https://virtserver.swaggerhub.com/doong3373/AfterMeal/1.0.0

tags:
  - name: Users
    description: 사용자 관련 엔드포인트
  - name: Activity
    description: 활동 관련 엔드포인트
  - name: Activity Locations
    description: 활동 장소 관련 엔드포인트
  - name: Authentication
    description: 인증 관련 엔드포인트

paths:
  /users:
    post:
      tags:
        - Users
      operationId: UserController_register
      summary: 사용자 등록
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UserRegistrationRequestDto"
      responses:
        201:
          description: OK
        400:
          description: Bad Request
        404:
          description: Not Found
        409:
          description: Conflict

    get:
      tags:
        - Users
      summary: 사용자 목록 조회
      security:
        - bearerAuth: []
      responses:
        200:
          description: Successful response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/UserListResponseDto"

  /users/{userId}:
    patch:
      tags:
        - Users
      summary: 사용자 수정
      security:
        - bearerAuth: []
      parameters:
        - name: userId
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UserUpdateRequestDto"
      responses:
        200:
          description: User updated successfully

    delete:
      tags:
        - Users
      summary: 사용자 삭제
      security:
        - bearerAuth: []
      parameters:
        - name: userId
          in: path
          required: true
          schema:
            type: integer
      responses:
        204:
          description: User deleted successfully

  /activities:
    post:
      tags:
        - Activity
      summary: 활동 생성
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ActivityCreatationRequestDto"
      responses:
        201:
          description: Activity Schedule created successfully

    get:
      tags:
        - Activity
      summary: 활동 목록 조회
      responses:
        200:
          description: Successful response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/ActivityListResponseDto"

  /activities/{activityId}:
    get:
      tags:
        - Activity
      summary: 활동 상세 조회
      parameters:
        - name: activityId
          in: path
          required: true
          schema:
            type: integer
      responses:
        200:
          description: Successful response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ActivityResponseDto"

    patch:
      tags:
        - Activity
      summary: 활동 수정
      security:
        - bearerAuth: []
      parameters:
        - name: activityId
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ActivityUpdateDto"
      responses:
        200:
          description: Activity updated successfully

    delete:
      tags:
        - Activity
      summary: 활동 삭제
      security:
        - bearerAuth: []
      parameters:
        - name: activityId
          in: path
          required: true
          schema:
            type: integer
      responses:
        204:
          description: Activity Schedule deleted successfully

  /activity/{activityId}/joins:
    post:
      tags:
        - Activity
      summary: 활동 참가
      security:
        - bearerAuth: []
      parameters:
        - name: activityId
          in: path
          required: true
          schema:
            type: integer
      responses:
        201:
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ActivityJoinRequestDto"

  /activity/{activityId}/joins/{joinId}:
    delete:
      tags:
        - Activity
      summary: 활동 참가 취소
      security:
        - bearerAuth: []
      parameters:
        - name: activityId
          in: path
          required: true
          schema:
            type: integer
        - name: joinId
          in: path
          required: true
          schema:
            type: integer
      responses:
        204:
          description: Join deleted successfully

  /activity-locations:
    post:
      tags:
        - Activity Locations
      summary: 활동 장소 생성
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ActivityLocationCreationRequestDto"
      responses:
        201:
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ActivityLocationCreationResponseDto"

    get:
      tags:
        - Activity Locations
      summary: 활동 장소 목록 조회
      security:
        - bearerAuth: []
      responses:
        201:
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ActivityLocationListResponseDto"
    
  /activity-locations/{activityLocationId}:
    patch:
      tags:
        - Activity Locations
      summary: 활동 장소 수정
      security:
        - bearerAuth: []
      parameters:
        - name: activityLocationId
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ActivityLocationUpdateRequestDto"
      responses:
        201:
          description: OK

    delete:
      tags:
        - Activity Locations
      summary: 활동 장소 삭제
      security:
        - bearerAuth: []
      parameters:
        - name: activityLocationId
          in: path
          required: true
          schema:
            type: integer
      responses:
        201:
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ActivityLocationListResponseDto"

  /auth/login:
    post:
      tags:
        - Authentication
      summary: 로그인
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/LoginRequestDto"
      responses:
        200:
          description: Login successful
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/LoginResponseDto"

  /auth/refresh:
    post:
      operationId: AuthController_refresh
      summary: 토큰 갱신
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/TokenRefreshRequestDto"
      responses:
        201:
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/TokenRefreshResponseDto"
        400:
          description: Bad Request
      tags:
        - Authentication

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    UserRegistrationRequestDto:
      type: object
      properties:
        name:
          type: string
        email:
          type: string
        type:
          type: string
          enum:
            - STUDENT
            - TEACHER
        generationNumber:
          type: number
          minimum: 1
        password:
          type: string
      required:
        - name
        - email
        - type
        - password

    UserListResponseDto:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        email:
          type: string
        roles:
          type: array
          items:
            type: string
            enum: [USER, ADMIN]
        type:
          type: string
          enum: [STUDENT, TEACHER]
        status:
          type: string
          enum: [ACTIVATE, DEACTIVATE]
        generationNumber:
          type: integer
          minimum: 1
      required:
        - id
        - name
        - email
        - roles
        - type
        - status
        - generationNumber

    UserUpdateRequestDto:
      type: object
      properties:
        name:
          type: string
        type:
          type: string
          enum: [STUDENT, TEACHER]
        status:
          type: string
          enum: [ACTIVATE, DEACTIVATE]
        generationNumber:
          type: integer
          minimum: 1

    ActivityCreatationRequestDto:
      type: object
      properties:
        title:
          type: string
        maxParticipants:
          type: integer
          minimum: 1
        location:
          type: string
        type:
          type: string
          enum: [LUNCH, DINNER]
        scheduledDate:
          type: string
          format: date
      required:
        - title
        - maxParticipants
        - location
        - type
        - scheduledDate

    ActivityListResponseDto:
      type: object
      properties:
        id:
          type: integer
        title:
          type: string
        maxParticipants:
          type: integer
        currentParticipants:
          type: integer
        location:
          type: string
        status:
          type: string
          enum: [SCHEDULED, IN_PROGRESS, CANCELED, COMPLETED]
        type:
          type: string
          enum: [LUNCH, DINNER]
        scheduledDate:
          type: string
          format: date
        applicationStartDate:
          type: string
          format: date-time
        applicationEndDate:
          type: string
          format: date-time

    ActivityResponseDto:
      type: object
      properties:
        id:
          type: integer
        title:
          type: string
        maxParticipants:
          type: integer
        status:
          type: string
          enum: [SCHEDULED, IN_PROGRESS, CANCELED, COMPLETED]
        type:
          type: string
          enum: [LUNCH, DINNER]
        scheduledDate:
          type: string
          format: date
        applicationStartDate:
          type: string
          format: date-time
        applicationEndDate:
          type: string
          format: date-time
        participants:
          type: array
          items:
            type: object
            properties:
              id:
                type: integer
              displayName:
                type: string

    ActivityUpdateDto:
      type: object
      properties:
        title:
          type: string
        maxParticipants:
          type: integer
          minimum: 1
        location:
          type: string
        status:
          type: string
          enum: [SCHEDULED, IN_PROGRESS, CANCELED, COMPLETED]
        type:
          type: string
          enum: [LUNCH, DINNER]
        scheduledDate:
          type: string
          format: date
        applicationStartDate:
          type: string
          format: date-time
        applicationEndDate:
          type: string
          format: date-time

    ActivityJoinRequestDto:
      type: object
      properties:
        activityId:
          type: number
          minimum: 1
      required:
        - activityId

    ActivityLocationCreationRequestDto:
      type: object
      properties:
        name:
          type: string
      required:
        - name

    ActivityLocationCreationResponseDto:
      type: object
      properties:
        id:
          type: number
          minimum: 1
        name:
          type: string
      required:
        - id

    ActivityLocationListResponseDto:
      type: object
      properties:
        id:
          type: number
          minimum: 1
        name:
          type: string

    ActivityLocationUpdateRequestDto:
      type: object
      properties:
        name:
          type: string

    LoginRequestDto:
      type: object
      properties:
        email:
          type: string
        password:
          type: string
      required:
        - email
        - password

    LoginResponseDto:
      type: object
      properties:
        accessToken:
          type: string
        tokenType:
          type: string
        expiredIn:
          type: integer
        refreshToken:
          type: string
        user:
          type: object
          properties:
            id:
              type: string
            name:
              type: string
            roles:
              type: array
              items:
                type: string
                enum: [USER, ADMIN]
      required:
        - accessToken
        - tokenType
        - expiredIn
        - refreshToken
        - user

    TokenRefreshRequestDto:
      type: object
      properties:
        refreshToken:
          type: string
      required:
        - refreshToken

    TokenRefreshResponseDto:
      type: object
      properties:
        accessToken:
          type: string
        tokenType:
          type: string
        expiredIn:
          type: number
        refreshToken:
          type: string
      required:
        - accessToken
        - tokenType
        - expiredIn
        - refreshToken
